### ISSUE TITLE
StackOverflow search is broken

### ISSUE THREAD

**Issue by smarmy** [gurka/bertil#29]
Stackoverflow search gives largely irrelevant answers to queries.

Example:
simon [3:25 PM] 
so std::move

bertilAPP [3:25 PM] 
@simon: The ability to chain
```or```
clause along with
```where```
clause in
```ActiveRecord```
query will be available in **Rails 5**. See the <a href="https://github.com/rails/rails/pull/16052">related discussion and the pull request</a>.
So, you will be able to do the following things in **Rails 5**:
To get a
```post```
with
```id```
1 or 2:
```Post.where('id = 1').or(Post.where('id = 2'))
```
Some other examples:
...
https://stackoverflow.com/a/32753177
stackoverflow.com
Rails 5: ActiveRecord OR query
How do you do an or query in Rails 5 ActiveRecord? Also, is it possible to chain or with where in ActiveRecord queries?

**Comment by gurka** [comment]
Introduced in e03774204b90c28fa2e22ab53f455cdb95633e7e

Assigning @smarmy to issue

**Comment by gurka** [comment]
Fixed with c73f38a0a928712d50f5199fceb58892111a868e.
